sudo: false
language: julia
os:
    - osx
    - linux

julia:
    - 0.4
    - 0.5
    - nightly

notifications:
    email: false

addons:
  apt:
    packages:
    - gfortran

matrix:
  allow_failures:
    - os: osx # allow OS X to fail until intermittent failures can be resolved.

#script:  # use the default scipt which is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Dierckx"); Pkg.test("Dierckx"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Dierckx")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
