sudo: false
language: julia
os:
  - osx
  - linux
  - freebsd

julia:
    - 1.4
    - 1
    - nightly

coveralls: true

notifications:
    email: false

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts
