sudo: false
language: julia
os:
    - osx
    - linux

julia:
    - 0.7
    - nightly

notifications:
    email: false

addons:
  apt:
    packages:
    - gfortran

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install gcc || brew link --overwrite gcc; fi

#matrix:
#  allow_failures:
#    - os: osx # allow OS X to fail until intermittent failures can be resolved.

after_success:
  - julia -e 'cd(Pkg.dir("Dierckx")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
