name = "Dierckx"
uuid = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
repo = "https://github.com/kbarbary/Dierckx.jl.git"
version = "0.5.0"

[deps]
Dierckx_jll = "cd4c43a9-7502-52ba-aa6d-59fb2a88580b"

[compat]
Dierckx_jll = "0.0.1"
julia = "1.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
